### ISSUE TITLE
Skip workflows if executed processes are not in the list of processes / process levels

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-test-suite#10]
Workflow tests should only run if executed processes are in the list of processes / process levels, otherwise they should be skipped.

See fixtures `processes` and `process_levels`.

**Comment by clausmichele** [comment]
How do we do with load_stac? If not present I should try to use an openEO collection with which name?

**Comment by m-mohr** [comment]
In other tests I simply skipped tests that can't be fulfilled by the backend due to missing processes, unless a given processing level requires the process (then it should be reported as error).

**Comment by clausmichele** [comment]
But then it would be impossible to test the SentinelHub back-end or any other back-end not yet supporting `load_stac`, but able to index the sample collection, despite `load_stac` not being a process of the L1.

**Comment by clausmichele** [comment]
@m-mohr a couple of things:
1. Are the conformance level public already? I know they are here, but it's a private repo: https://github.com/openEOPlatform/architecture-docs/blob/master/interface/processes/results/profiles.md
2. Should we also document the tests that are skipped due to a missing process? Skipping them directly would not be so informative imho.

**Comment by m-mohr** [comment]
You can of course also make it configurable to provide a collection ID, but if neither a collection ID nor load_stac is abailable, skip it with a notice. I also do it that way in my tests, feel free to check it for examples.

1. Yes, published on https://openeo.org/documentation/1.0/developers/profiles/api.html and https://openeo.org/documentation/1.0/developers/profiles/processes.html
2. I skip them with a message, see my examples. Show them with the -rs flag in the CLI.

**Comment by clausmichele** [comment]
Implemented in the last commit: https://github.com/Open-EO/openeo-test-suite/commit/39c9ec423f35d860bf10c1256ece523c5e95f8aa
