### ISSUE TITLE
Skip workflows if file format not supported

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-test-suite#11]
In this commit https://github.com/Open-EO/openeo-test-suite/commit/28d0363c19d081038134e323634db72aee24a5ae, I implemented a check on the available file formats for the test_load_save.py.
However, it would be better to skip all the tests at module level in the case netCDF is missing, since in the other tests netCDF is always used.

I looked around but I wasn't able to use a fixture with `pytest.mark.skipif` https://docs.pytest.org/en/7.1.x/how-to/skipping.html

Maybe @soxofaan will be able to help finding a solution after the holidays.

**Comment by soxofaan** [comment]
`pytest.mark.skipif` is not possible with fixtures I think, as `pytest.mark.skipif` is done at "test collection" phase, while the fixtures are created later, just in time at "test execution" phase.

Alternatively, to trim down on boilerplate, you could do something like 

```python

def skip_if_no_netcdf_support(connection):
    if ...:
        pytest.skip("No netCDF support")

...

def test_something_with_netcdf(connection):
    skip_if_no_netcdf_support(connection)
    ...

```

Then you only need a single line `skip_if_no_netcdf_support(connection)` in each test that requires NetCDF support, which is reasonable I think

**Comment by clausmichele** [comment]
@soxofaan I tried your way but couldn't get a functional code, I implemented the check in the same way also for the other workflows. Not a one-liner but it works.

**Comment by soxofaan** [comment]
in 5c926b0b3cc871e166a60cfe0ded098726b5b82b I implemented an alternative way to reduce the boilerplate code around skipping
