### ISSUE TITLE
Validation of Collections

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-test-suite#13]
I'm starting creating the tests for the openEO Collections, here some questions. I use the VITO back-end as an example https://openeo.vito.be/openeo/1.0

1. https://api.openeo.org/#tag/Capabilities/operation/capabilities : _id (required) | string Identifier for the service. This field originates from STAC and is used as unique identifier for the STAC catalog available at /collections._
from this line, I would understand two things:
    1. The endpoint https://openeo.vito.be/openeo/1.0/collections should return a STAC Catalog
    2. The `id` field should be present under https://openeo.vito.be/openeo/1.0/collections

However, ine the API specs there's no mention about a STAC Catalog for the /collections endpoint https://api.openeo.org/#tag/EO-Data-Discovery/operation/list-collections

So the question is: is the /collections endpoint supposed to be a valid STAC Catalog or not?
@m-mohr

**Comment by m-mohr** [comment]
You are mixing multiple endpoints up here?

- GET / is a STAC catalog, i.e. the API landing page, id must be present top-level
- GET /collections is an API list of collections, is must be present for each collection

**Comment by clausmichele** [comment]
This sentence confuses me, since I understand that the /collections endpoint should return a STAC Catalog:
_This field originates from STAC and is used as unique identifier **for the STAC catalog available at /collections.**_

**Comment by m-mohr** [comment]
That's a bit unclear indeed, this should likely be more like:

> This field originates from STAC and is used as unique identifier for the STAC API made available (see /collections).
