### ISSUE TITLE
Invalid assets/processes submodule

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-test-suite#15]
@m-mohr the assets/processes submodule you added in 44a15ea1ff43307e9920588e6012545be86fc041 and updated a couple of times does not point to a publicly existing commit

at the moment it points to https://github.com/Open-EO/openeo-processes/tree/7e5df62673e1d9dbe5c37cda7b33cc399332b37d which github manages to resolve, but I can not check it out or inspect it in a local clone.

```
# In fully fetched openeo-processes clone
$ git show 7e5df62673e1d9dbe5c37cda7b33cc399332b37d
fatal: bad object 7e5df62673e1d9dbe5c37cda7b33cc399332b37d

# in openeo-test-suite clone
$ git submodule update --init
fatal: Needed a single revision
fatal: Unable to find current revision in submodule path 'assets/processes'
```

**Comment by soxofaan** [comment]
I just quick fixed it indeed to get out of the corrupted state, but you might have a better fix

**Comment by m-mohr** [comment]
Should be fine now, thanks.
