### ISSUE TITLE
Loop tests over collections

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-test-suite#18]
@soxofaan I implemented the tests for the collections, you can try with:
```
pytest --openeo-backend-url=https://openeo.vito.be/openeo/1.2
```

However, I'm not fully satisfied, since I needed to use an additional package (delayed_assert) to obtain what I plan to do.
I still didn't add the `delayed_assert` package to the requirements because I would like to find a way to avoid using it.

The problem occurs when I loop over the collections. Using normal `assert`, the first failing would stop the testing of all the other collections in the loop: https://github.com/Open-EO/openeo-test-suite/blob/ce9c834251fb683391b4cb4397ecf97e7db773c5/src/openeo_test_suite/tests/collections/test_collections.py#L62

I also tried to use `pytest.mark.parametrize` https://github.com/Open-EO/openeo-test-suite/blob/ce9c834251fb683391b4cb4397ecf97e7db773c5/src/openeo_test_suite/tests/collections/test_collections.py#L45-L46
but the problem here is that the list of collection ids can't be generated from a fixture.

The solution would be to find a way to initialize a list of collection ids at the beginning and then reuse it later in combination with pytest parametrize. Do you have an idea on how to achieve this?

**Comment by soxofaan** [comment]
@clausmichele  I implemented (merged in main already) a plugin for collection id based parameterization, e.g.:

```
from openeo_test_suite.lib.backend_under_test import get_collection_ids


@pytest.mark.parametrize("collection_id", get_collection_ids())
def test_valid_collection_id(collection_id: str):
    assert re.match(r"^[\w\-.~/]+$", collection_id, flags=re.IGNORECASE)
```

I tried to port the existing test_collections.py too (and eliminate delayed_assert usage)
