### ISSUE TITLE
WP3: Implement "validation of process metadata" tests in framework

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-test-suite#19]
WP3: Validation of process metadata
Lead partner: EODC

to be implemented in current framework
placeholder folder provided at https://github.com/Open-EO/openeo-test-suite/tree/main/src/openeo_test_suite/tests/processes/metadata

**Comment by christophreimer** [comment]
@soxofaan can you please assign this issue to @GeraldIr

**Comment by soxofaan** [comment]
@christophreimer @GeraldIr Is there any news or updates already about this?

**Comment by soxofaan** [comment]
FYI: I also added some TODO notes for this ticket to the root [README.md](https://github.com/Open-EO/openeo-test-suite/blob/main/README.md):

> `TODO: Open-EO/openeo-test-suite#19`

**Comment by christophreimer** [comment]
> FYI: I also added some TODO notes for this ticket to the root [README.md](https://github.com/Open-EO/openeo-test-suite/blob/main/README.md):
> 
> > `TODO: Open-EO/openeo-test-suite#19`

Thank you @soxofaan, as already discussed, the entire framework for process metadata validation is available in [https://github.com/Open-EO/openeo-compliance-checker](https://github.com/Open-EO/openeo-compliance-checker) since December 2023. What is missing is the integration of [https://github.com/Open-EO/openeo-compliance-checker](https://github.com/Open-EO/openeo-compliance-checker) into this repo.

**Comment by soxofaan** [comment]
>  as already discussed, the entire framework for process metadata validation is available in https://github.com/Open-EO/openeo-compliance-checker since December 2023. What is missing is the integration of https://github.com/Open-EO/openeo-compliance-checker into this repo.

You indeed stated that before, but as far as I understand, you just pushed an internal tool to as private reop on gihub. Looking at the history of https://github.com/Open-EO/openeo-compliance-checker  no significant commits happened after the kickoff of the project. I see in the proposal that EODC allocated 187 hours effort in the proposal, but so far zero commits have been made to https://github.com/Open-EO/openeo-test-suite which is the central deliverable.  

I also tried to run your test suite, but had a hard time to get it working (I already [submitted some tickets](https://github.com/Open-EO/openeo-compliance-checker/issues)). It feels very rough around the edges and not ready for broad usage yet. I think there is quite some effort necessary to make it usable and integrate it properly in the  openeo-test-suite framework, as promised in the project proposal.

You promised to do the integration several times before, but nothing happend yet and we're already past multiple (delayed) deadlines

**Comment by soxofaan** [comment]
done by #44
