### ISSUE TITLE
Parse process examples in JSON5 format

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-test-suite#2]
the process examples to use in the "individual process testing" are written as JSON5: https://github.com/Open-EO/openeo-processes/tree/add-tests/tests

I already found a couple of options to read JSON5:
- https://github.com/dpranke/pyjson5 (https://pypi.org/project/json5/)
- https://github.com/Kijewski/pyjson5 (https://pypi.org/project/pyjson5/)
- https://github.com/spyoungtech/json-five (https://pypi.org/project/json-five/)

I have no idea yet on which one to bet at the moment

**Comment by soxofaan** [comment]
nope, no support for other JSON5 features like comments, unquoted keys, single quotes, trailing coma

**Comment by m-mohr** [comment]
It really only uses comments, all other features I'm trying not to use. If it's much simpler to implement I could also use a "$comment" property as in JSON schema.

**Comment by soxofaan** [comment]
Stripping commas before json parsing will also be pretty easy  to do DIY-style (regex oneliner) without the need for full fledge JSON5 library.

**Comment by m-mohr** [comment]
You mean comments, not commas, right?
But yes indeed. A simple regex should be able to cater for that and then it could go into the native Python JSON module.

**Comment by soxofaan** [comment]
> You mean comments, not commas, right?

Indeed.

but now that you mention it: DIY-stripping trailing comma's shouldn't be that hard either

**Comment by m-mohr** [comment]
Yes, but I'll try to ensure that we only need to strip comments and handle NaN/Infinity. Otherwise, I'll stick to pure JSON for now.
