### ISSUE TITLE
WP4: General API compliance validation

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-test-suite#20]
WP4: General API compliance validation
Lead partner: EODC

**Comment by christophreimer** [comment]
@soxofaan can you please add @GeraldIr here as assignee as well

**Comment by soxofaan** [comment]
@christophreimer  @GeraldIr  Is there any news or updates already about this?

**Comment by GeraldIr** [comment]
The code for this already exists in the https://github.com/Open-EO/openeo-compliance-checker repo. I'll see to transferring/adapting the code for this repo soon.

**Comment by m-mohr** [comment]
The deadline set for this was agreed to be yesterday (or maybe tomorrow, can't recall). So "soon" is rather late... @GeraldIr 
Can you be more specific?

**Comment by soxofaan** [comment]
FYI: I also added some TODO notes for this ticket to the root [README.md](https://github.com/Open-EO/openeo-test-suite/blob/main/README.md):

> `TODO: Open-EO/openeo-test-suite#20`
