### ISSUE TITLE
--openeo-backend-url overly long?

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-test-suite#22]
To me --openeo-backend-url seems overly long. We are lazy programmers. Why not just --url or so? ;-)

**Comment by soxofaan** [comment]
This bugged me in practice as well. Maybe `--backend` is less generic and still short enough. 
We can also add a short variant, like "-u", but I'm not sure how easy it then is to avoid conflicts

**Comment by m-mohr** [comment]
What kind of conflicts?

**Comment by soxofaan** [comment]
With other plugins we might add later. But I'm just about to push a commit that adds the short version `-U` (apparently short options have to be upper case)
