### ISSUE TITLE
Individual process testing doesn't run against local runners anymore

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-test-suite#23]
When the individual process testing was included into this repo, I was able to run:
`pytest src/openeo_test_suite/tests/processes/processing/test_example.py --runner=dask` 
as documented in the corresponding README.
I want to run against the local dask installation

If I'm running it now it says that --openeo-backend-url is not provided.

**Comment by soxofaan** [comment]
thanks for reporting, I'll work on that

**Comment by soxofaan** [comment]
pushed a quickfix already

**Comment by soxofaan** [comment]
I think this can be closed now
