### ISSUE TITLE
unused find_callback_parameters?

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-test-suite#26]
https://github.com/Open-EO/openeo-test-suite/blob/abe6f67801f66a27be7e9c933cbf8db9c601723a/src/openeo_test_suite/lib/process_runner/util.py#L109-L126

@m-mohr I can't find any usage of this `find_callback_parameters`.
Can it be removed, or is it there for a reason?

**Comment by m-mohr** [comment]
Can be removed, I think: https://github.com/Open-EO/openeo-test-suite/issues/27#issuecomment-1901170799

**Comment by soxofaan** [comment]
thanks, removed it
