### ISSUE TITLE
ProcessTestRunner: list_processes and describe_process

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-test-suite#27]
https://github.com/Open-EO/openeo-test-suite/blob/abe6f67801f66a27be7e9c933cbf8db9c601723a/src/openeo_test_suite/lib/process_runner/base.py#L5-L17

@m-mohr I'm trying to understand what these methods `list_processes` and `describe_process` are for. I can't find where they are used (except for `find_callback_parameters`, but that's also unused to I think: #26)

**Comment by m-mohr** [comment]
list_processes was used to get the processes a backend supports, that should still be relevant for getting the specific processes for dask etc. 

descibe_process and find_callback_parameters look unused, indeed. I assume that was an experiment that I forgot to delete, can be removed, I think.

**Comment by soxofaan** [comment]
thanks, removed `descibe_process`, but kept `list_processes` which is indeed a necessary part of the API (#31 related)
