### ISSUE TITLE
Simplify configuration: drop env var support

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-test-suite#29]
We now have various config options `--experimental`, `--process-levels`, `--runner` , `--processes`, but each of these can also be set through environment variables
e.g. `OPENEO_EXPERIMENTAL` for `--experimental`, `OPENEO_PROCESS_LEVELS` for `--process-levels`, etc.

This requires quite some repetitive boilerplate logic in various fixtures, and documentation overhead (still TODO).

I wonder if there is actual need to configure the test suite run through env vars and if we can't simplify the implementation and usage docs by just dropping the env var approach.

I guess we just grew into this situation by copy-pasting one of the original fixtures I set up initially, but it feels like the added value of that approach has become negative.

any thoughts @m-mohr  @clausmichele ?

**Comment by soxofaan** [comment]
I also noticed the env var support  made default value handling a lot more cumbersome

**Comment by m-mohr** [comment]
From my side ENV variables can be removed, I never use them.

**Comment by clausmichele** [comment]
Same on my side, let's just use the provided options
