### ISSUE TITLE
Some warnings are not captured by pytest

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-test-suite#33]
Some warnings are not correctly captured by pytest after the changes in #27.

Instead of showing up in the warnings summary:
![grafik](https://github.com/Open-EO/openeo-test-suite/assets/8262166/e386b396-76d8-43db-ae75-81378fcf53a1)

They now show up in the live log setup:
![grafik](https://github.com/Open-EO/openeo-test-suite/assets/8262166/6a65efbb-db25-4733-ae08-b977c1af966b)

That is confusing. They are also not identified as warnings by pytest. Is there a way to fix this, @soxofaan ?

_Originally posted by @m-mohr in https://github.com/Open-EO/openeo-test-suite/issues/32#issuecomment-1903709605_

Code to run this: `pytest src/openeo_test_suite/tests/processes/processing/test_example.py --runner=dask --log-cli-level=WARN --processes divide,array_append > output.txt`

**Comment by soxofaan** [comment]
I'm just going to revert this warning to `warnings.warn` if that makes more sense to you.
This is warning is basically a todo that has to be addressed anyway, it's not worth it to overthink if this has to be `logging.warning` vs `warnings.warn`

**Comment by soxofaan** [comment]
one minor thing: I changed the warning message from `...but got {result.__class__}` to `...but got {result!r}` because the latter gives more information and context (exception class + message) instead of just exception class
