### ISSUE TITLE
Command line default parameters are not as described

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-test-suite#52]
I just tried to run again the test suite after some time and I noticed that most of the (workflows) tests are skipped.

I'm running it with:
```bash
pytest src/openeo_test_suite/tests/workflows \
--openeo-backend-url=https://openeo.dataspace.copernicus.eu/openeo/1.2  \
--s2-collection=https://stac.eurac.edu/collections/SENTINEL2_L2A_SAMPLE_2 \
--html=reports/workflows.html
```

without explicitly passing --processes or --levels it should test all the processes, but it skips all of them instead:`"Skipped: Process selection does not cover: {'clip', 'load_stac', 'apply'}")`

how do I just run all the tests?

**Comment by soxofaan** [comment]
> Regardless, the docs need some more work to better cover this

or even better: `load_stac` should be "allow-listed" automatically if the STAC based data loading is used for the workflow tests

**Comment by clausmichele** [comment]
> Can you confirm that this fixes your original problem.
> 
> Regardless, the docs need some more work to better cover this

Adding the experimental flag doesn't seem to change anything, it still skips all the tests:

`pytest src/openeo_test_suite/tests/workflows --openeo-backend-url=https://openeo.dataspace.copernicus.eu/openeo/1.2  --s2-collection=https://stac.eurac.edu/collections/SENTINEL2_L2A_SAMPLE_2 --html=reports/workflows.html --experimental`

**Comment by clausmichele** [comment]
After creating a new environment it also works for me, thanks for the support @soxofaan.
