### ISSUE TITLE
test_assets() should not check "collection-assets" for 0.x.x versions

### ISSUE THREAD

**Issue by Jay-Gohil** [Open-EO/openeo-test-suite#53]
test_assets() method is checking existence of "collection-assets" in "stac_extensions" for versions starting with 0.x. However, this is not correct as collection-assets extension was defined only for versions 1.0.0-beta.1 and 1.0.0-beta.2. It doesn't exists e.g. for 0.9.0 (there is a 'assets' extension proposal for that version, but not collection-assets).

Here are the relevant links:

https://github.com/radiantearth/stac-spec/blob/v0.9.0/extensions/collection-assets/README.md (page not found, i.e. extension doesn't exist)
https://github.com/radiantearth/stac-spec/blob/v1.0.0-beta.1/extensions/collection-assets/README.md (page exists)
https://github.com/radiantearth/stac-spec/blob/v1.0.0-beta.2/extensions/collection-assets/README.md (page exists)
https://github.com/radiantearth/stac-spec/blob/v1.0.0-rc.1/extensions/collection-assets/README.md (page not found, i.e. extension doesn't exist - in fact, it is not necessary, as assets become part of the collection specification)

One example collection for which the test fails: https://openeo.dataspace.copernicus.eu/openeo/1.2/collections/SENTINEL1_GRD

**Comment by soxofaan** [comment]
https://github.com/Open-EO/openeo-test-suite/blob/4d03e80ac1bc93f2738e18a64aed16eecaed4690/src/openeo_test_suite/tests/collections/openeo_api_collection_tests.py#L111-L122

This test checks for this part of the openEO spec (https://github.com/Open-EO/openeo-api/blob/c5a45b4647b06e313a4f099e9119bfa3cca5c6a3/openapi.yaml#L4514-L4521) about the "assets" property in collection metadata:
> Implementing this property REQUIRES to add `collection-assets` to the list of stac_extensions in STAC < 1.0.0-rc.1.


But indeed,  "collection-assets" is not an valid core extension in STAC 0.0.9 or earlier, as it was only introduced in STAC 1.0.0-beta.1.

@m-mohr  does this mean that the openEO spec should actually state something like
> Implementing this property REQUIRES to add `collection-assets` to the list of stac_extensions when 1.0.0-beta.1 <= `stac_version` < 1.0.0-rc.1.


In any case, the current implementation of `test_assets` is a bit off as it naively checks if the version starts with `0.`, while it should also include `1.0.0-beta.1` and `1.0.0-beta.2` (the only `1.x` versions below `1.0.0-rc.1`)

**Comment by soxofaan** [comment]
looping @clausmichele  too

**Comment by m-mohr** [comment]
That's all correct. But I'd like to note that we should deprecate STAC < 1.0.0 in openEO anyway. With that we may also just already remove those < 1.0.0 requirements completely.

**Comment by clausmichele** [comment]
Thanks for the fix @soxofaan!
